version: 3;

services:
  server:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: server
    command: "npm run start:prod"
    depends_on:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
  db:
    image: postgres:16.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=comments
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
volumes:
  db:
    driver: local